# Generated by Django 5.2.12 on 2026-04-03 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pymess", "0034_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessage",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "waiting"),
                    (2, "sending"),
                    (3, "sent"),
                    (4, "error"),
                    (5, "debug"),
                    (6, "error retry"),
                    (7, "opened"),
                ],
                db_index=True,
                editable=False,
                verbose_name="state",
            ),
        ),
    ]
