name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        django-version: ["4.2"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          setup.py
          requirements-dev.txt
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install "django==${{ matrix.django-version }}.*"
        pip install -e .
        pip install coverage coveralls
    
    - name: Run tests
      run: |
        coverage run --source=pymess -m pytest
        coverage report
        coverage xml
        coverage lcov

    - name: Upload coverage to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: coverallsapp/github-action@v2
      with:
        file: coverage.lcov
        flag-name: python-${{ matrix.python-version }}-django-${{ matrix.django-version }}
        parallel: true

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true